name: Build and Deploy

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: [self-hosted, vossatandem-web]
    environment: deploy
    env:
      DEPLOY_TARGET_PATH: ${{ secrets.DEPLOY_TARGET_PATH }}
    steps:
    - uses: actions/checkout@v3
    - name: Build and Deploy
      run: .\deploy.ps1
